image: "python:3.8.16-slim"

before_script:
  - python --version
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

stages:
  - Static Analysis

flake8-mypy-pylint:
  stage: Static Analysis
  allow_failure: false
  script:
  - flake8 --max-line-length=120 --max-complexity=10 src
  - mypy --disable-error-code import --disable-error-code attr-defined --show-error-codes src
  - pylint --disable=E0401,C0301,C0114,C0115,C0116,C0103 --fail-under 9.0 src
